export { default as heroSliderData } from './datas/heroSlider'
export { default as productData } from './datas/products'
export { default as list } from './datas/list'
export { default as size } from './datas/product-size'
export { default as colors } from './datas/product-color'
export { default as category } from './datas/category'