export { default as Tabname } from './Tab/Tabname'
export { default as HeroSlider } from './Home/Slider/HeroSlider'
export { default as Products } from './Home/Products/Products'
export { default as List } from './Home/List/List'
export { default as Footer } from './Footer/Footer'