// DETAIL PRODUCT LIST
export const DETAIL_PRODUCT_REQUEST = "DETAIL_PRODUCT_REQUEST"
export const DETAIL_PRODUCT_SUCCESS = "DETAIL_PRODUCT_SUCCESS"
export const DETAIL_PRODUCT_FAIL = "DETAIL_PRODUCT_FAIL"
